"""contact requests lead capture

Revision ID: af80fbe033ec
Revises: a1b2c3d4e5f6
Create Date: 2026-07-09 02:53:40.090355+00:00

Creates the onboarding lead table AND re-runs scripts/enable_rls.sql
(idempotent) so the new table is grant-covered, RLS-forced and gated by
the ``platform_only`` policy in the same deployment step — a migrated
database is never left with an unprotected table.
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

_RLS_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "enable_rls.sql"

revision: str = 'af80fbe033ec'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONVERTED', 'REJECTED', name='contact_request_status'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_requests'))
    )
    op.create_index(op.f('ix_contact_requests_status'), 'contact_requests', ['status'], unique=False)
    # ### end Alembic commands ###

    # Re-apply the security posture so contact_requests gets its grants,
    # ENABLE/FORCE RLS and the platform_only policy (script is idempotent).
    sql = _RLS_SCRIPT.read_text(encoding="utf-8")
    sql = sql.replace("\nBEGIN;\n", "\n").replace("\nCOMMIT;\n", "\n")
    op.get_bind().exec_driver_sql(sql)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_requests_status'), table_name='contact_requests')
    op.drop_table('contact_requests')
    # ### end Alembic commands ###
