"""food item image url

Revision ID: b200544361f8
Revises: f6755ca9f68a
Create Date: 2026-07-12 12:30:32.489434+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b200544361f8'
down_revision: Union[str, None] = 'f6755ca9f68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'image_url')
    # ### end Alembic commands ###
