"""b2c: GUEST role, relaxed user constraint, bookings.qpay_invoice_id

Revision ID: b7e1c9d2f4a3
Revises: 4838509f305a
Create Date: 2026-07-09 00:00:00.000000+00:00

Hand-written (not autogenerated): enum-value additions and CHECK-constraint
edits are things Alembic autogenerate handles poorly.

The 'GUEST' value is added in an autocommit block so it is COMMITTED before
the recreated CHECK constraint references it — PostgreSQL cannot use a new
enum value in the same transaction that adds it.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b7e1c9d2f4a3"
down_revision: Union[str, None] = "4838509f305a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_NEW_CHECK = (
    "(role = 'PLATFORM_ADMIN' AND tenant_id IS NULL AND restaurant_id IS NULL) "
    "OR (role = 'RESTAURANT_OWNER' AND restaurant_id IS NOT NULL "
    " AND tenant_id IS NULL) "
    "OR (role IN ('HOTEL_ADMIN', 'MANAGER', 'RECEPTION', 'CLEANER') "
    " AND tenant_id IS NOT NULL AND restaurant_id IS NULL) "
    "OR (role = 'GUEST' AND tenant_id IS NULL AND restaurant_id IS NULL)"
)
_OLD_CHECK = (
    "(role = 'PLATFORM_ADMIN' AND tenant_id IS NULL AND restaurant_id IS NULL) "
    "OR (role = 'RESTAURANT_OWNER' AND restaurant_id IS NOT NULL "
    " AND tenant_id IS NULL) "
    "OR (role IN ('HOTEL_ADMIN', 'MANAGER', 'RECEPTION', 'CLEANER') "
    " AND tenant_id IS NOT NULL AND restaurant_id IS NULL)"
)


def upgrade() -> None:
    # 1. Add the enum value in its own committed transaction.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'GUEST'")

    # 2. Relax the role/scope consistency check to permit GUEST.
    # Pass the LOGICAL name; the metadata naming convention expands it to
    # ck_users_role_realm_consistency (don't pre-expand, or it double-prefixes).
    op.drop_constraint("role_realm_consistency", "users", type_="check")
    op.create_check_constraint(
        "role_realm_consistency", "users", _NEW_CHECK
    )

    # 3. QPay invoice correlation column on bookings (unique, indexed).
    op.add_column(
        "bookings",
        sa.Column("qpay_invoice_id", sa.String(length=80), nullable=True),
    )
    op.create_index(
        op.f("ix_bookings_qpay_invoice_id"),
        "bookings",
        ["qpay_invoice_id"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_bookings_qpay_invoice_id"), table_name="bookings")
    op.drop_column("bookings", "qpay_invoice_id")
    # Pass the LOGICAL name; the metadata naming convention expands it to
    # ck_users_role_realm_consistency (don't pre-expand, or it double-prefixes).
    op.drop_constraint("role_realm_consistency", "users", type_="check")
    op.create_check_constraint("role_realm_consistency", "users", _OLD_CHECK)
    # Note: PostgreSQL cannot DROP an enum value; 'GUEST' remains on the type
    # (harmless — no rows use it after the constraint is restored).
