"""food order qpay invoice correlation

Revision ID: f6755ca9f68a
Revises: b7e1c9d2f4a3
Create Date: 2026-07-11 11:08:08.931763+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f6755ca9f68a'
down_revision: Union[str, None] = 'b7e1c9d2f4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_orders', sa.Column('qpay_invoice_id', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_food_orders_qpay_invoice_id'), 'food_orders', ['qpay_invoice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_orders_qpay_invoice_id'), table_name='food_orders')
    op.drop_column('food_orders', 'qpay_invoice_id')
    # ### end Alembic commands ###
