"""zero trust pin verification columns

Revision ID: 4b4454c4abd6
Revises: f361559f8a0b
Create Date: 2026-07-27 06:09:15.767206+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b4454c4abd6'
down_revision: Union[str, None] = 'f361559f8a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pin_code', sa.String(length=6), nullable=True))
    op.add_column('bookings', sa.Column('pin_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('bookings', sa.Column('override_requested', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'override_requested')
    op.drop_column('bookings', 'pin_verified')
    op.drop_column('bookings', 'pin_code')
    # ### end Alembic commands ###
