"""initial schema

Revision ID: 35d2dfee301a
Revises: 
Create Date: 2026-07-08 08:06:19.429046+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '35d2dfee301a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required by the bookings anti-double-booking GiST exclusion constraint.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_platform_accounts_balance_non_negative')),
    sa.CheckConstraint('commission_rate >= 0 AND commission_rate <= 0.5', name=op.f('ck_platform_accounts_commission_rate_sane')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_accounts'))
    )
    op.create_index('uq_platform_accounts_singleton', 'platform_accounts', [sa.literal_column('(true)')], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('maps_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('maps_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('subscription_plan', sa.Enum('3_MONTHS', '6_MONTHS', '9_MONTHS', '12_MONTHS', name='subscription_plan'), nullable=False),
    sa.Column('subscription_started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('subscription_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('maps_lat BETWEEN -90 AND 90', name=op.f('ck_tenants_maps_lat_range')),
    sa.CheckConstraint('maps_lng BETWEEN -180 AND 180', name=op.f('ck_tenants_maps_lng_range')),
    sa.CheckConstraint('subscription_expires_at > subscription_started_at', name=op.f('ck_tenants_subscription_window_valid')),
    sa.CheckConstraint('wallet_balance >= 0', name=op.f('ck_tenants_wallet_balance_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_index(op.f('ix_tenants_subscription_expires_at'), 'tenants', ['subscription_expires_at'], unique=False)
    op.create_table('wanted_persons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('registry_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('case_reference', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wanted_persons')),
    sa.UniqueConstraint('registry_hash', name=op.f('uq_wanted_persons_registry_hash'))
    )
    op.create_index(op.f('ix_wanted_persons_is_active'), 'wanted_persons', ['is_active'], unique=False)
    op.create_table('minibar_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_minibar_categories_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_minibar_categories'))
    )
    op.create_index(op.f('ix_minibar_categories_tenant_id'), 'minibar_categories', ['tenant_id'], unique=False)
    op.create_index('uq_minibar_categories_tenant_name', 'minibar_categories', ['tenant_id', 'name'], unique=True)
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('wallet_balance >= 0', name=op.f('ck_restaurants_wallet_balance_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_restaurants_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants'))
    )
    op.create_index(op.f('ix_restaurants_is_active'), 'restaurants', ['is_active'], unique=False)
    op.create_index(op.f('ix_restaurants_tenant_id'), 'restaurants', ['tenant_id'], unique=False)
    op.create_index('uq_restaurants_tenant_name', 'restaurants', ['tenant_id', 'name'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=16), nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'TWIN', 'FAMILY', 'SUITE', 'DELUXE', name='room_type'), nullable=False),
    sa.Column('beds', sa.SmallInteger(), nullable=False),
    sa.Column('floor', sa.SmallInteger(), nullable=False),
    sa.Column('state', sa.Enum('VACANT_CLEAN', 'OCCUPIED', 'VACANT_DIRTY', name='room_state'), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price >= 0', name=op.f('ck_rooms_base_price_non_negative')),
    sa.CheckConstraint('beds >= 1 AND beds <= 12', name=op.f('ck_rooms_beds_sane')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_rooms_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_index(op.f('ix_rooms_state'), 'rooms', ['state'], unique=False)
    op.create_index(op.f('ix_rooms_tenant_id'), 'rooms', ['tenant_id'], unique=False)
    op.create_index('uq_rooms_tenant_room_number', 'rooms', ['tenant_id', 'room_number'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_full_name', sa.String(length=255), nullable=False),
    sa.Column('guest_phone', sa.String(length=32), nullable=False),
    sa.Column('guest_email', sa.String(length=320), nullable=True),
    sa.Column('guest_registry_hash', sa.String(length=128), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW', name='booking_status'), nullable=False),
    sa.Column('nightly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('escrow_status', sa.Enum('NOT_FUNDED', 'HELD', 'RELEASED', 'REFUNDED', 'DISPUTED', name='escrow_status'), nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('escrow_settled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.text('room_id'), '='), (sa.text('daterange(check_in_date, check_out_date)'), '&&'), where=sa.text("status NOT IN ('CANCELLED', 'NO_SHOW')"), using='gist', name='excl_bookings_room_date_overlap'),
    sa.CheckConstraint('check_out_date > check_in_date', name=op.f('ck_bookings_dates_ordered')),
    sa.CheckConstraint('commission_amount >= 0 AND commission_amount <= total_amount', name=op.f('ck_bookings_commission_within_total')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_bookings_total_non_negative')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_bookings_room_id_rooms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bookings_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('code', name=op.f('uq_bookings_code'))
    )
    op.create_index(op.f('ix_bookings_escrow_status'), 'bookings', ['escrow_status'], unique=False)
    op.create_index(op.f('ix_bookings_guest_registry_hash'), 'bookings', ['guest_registry_hash'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_tenant_check_in', 'bookings', ['tenant_id', 'check_in_date'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_food_items_price_non_negative')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_food_items_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_items'))
    )
    op.create_index(op.f('ix_food_items_restaurant_id'), 'food_items', ['restaurant_id'], unique=False)
    op.create_index('uq_food_items_restaurant_name', 'food_items', ['restaurant_id', 'name'], unique=True)
    op.create_table('minibar_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_minibar_items_price_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['minibar_categories.id'], name=op.f('fk_minibar_items_category_id_minibar_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_minibar_items_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_minibar_items'))
    )
    op.create_index(op.f('ix_minibar_items_category_id'), 'minibar_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_minibar_items_tenant_id'), 'minibar_items', ['tenant_id'], unique=False)
    op.create_index('uq_minibar_items_tenant_name', 'minibar_items', ['tenant_id', 'name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'HOTEL_ADMIN', 'MANAGER', 'RECEPTION', 'CLEANER', 'RESTAURANT_OWNER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'PLATFORM_ADMIN' AND tenant_id IS NULL  AND restaurant_id IS NULL) OR (role = 'RESTAURANT_OWNER' AND restaurant_id IS NOT NULL  AND tenant_id IS NULL) OR (role IN ('HOTEL_ADMIN', 'MANAGER', 'RECEPTION', 'CLEANER')  AND tenant_id IS NOT NULL AND restaurant_id IS NULL)", name=op.f('ck_users_role_realm_consistency')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_users_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_restaurant_id'), 'users', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('food_orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PLACED', 'ACCEPTED', 'PREPARING', 'DELIVERED', 'CANCELLED', name='food_order_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('escrow_status', sa.Enum('NOT_FUNDED', 'HELD', 'RELEASED', 'REFUNDED', 'DISPUTED', name='escrow_status'), nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('escrow_settled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('commission_amount >= 0 AND commission_amount <= total_amount', name=op.f('ck_food_orders_commission_within_total')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_food_orders_total_non_negative')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_food_orders_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_food_orders_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_food_orders_room_id_rooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_food_orders_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_orders'))
    )
    op.create_index(op.f('ix_food_orders_booking_id'), 'food_orders', ['booking_id'], unique=False)
    op.create_index(op.f('ix_food_orders_escrow_status'), 'food_orders', ['escrow_status'], unique=False)
    op.create_index(op.f('ix_food_orders_restaurant_id'), 'food_orders', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_food_orders_status'), 'food_orders', ['status'], unique=False)
    op.create_index(op.f('ix_food_orders_tenant_id'), 'food_orders', ['tenant_id'], unique=False)
    op.create_table('minibar_consumptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('minibar_item_id', sa.UUID(), nullable=True),
    sa.Column('reported_by_user_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_minibar_consumptions_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_minibar_consumptions_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_minibar_consumptions_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['minibar_item_id'], ['minibar_items.id'], name=op.f('fk_minibar_consumptions_minibar_item_id_minibar_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], name=op.f('fk_minibar_consumptions_reported_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_minibar_consumptions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_minibar_consumptions'))
    )
    op.create_index(op.f('ix_minibar_consumptions_booking_id'), 'minibar_consumptions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_minibar_consumptions_is_settled'), 'minibar_consumptions', ['is_settled'], unique=False)
    op.create_index(op.f('ix_minibar_consumptions_tenant_id'), 'minibar_consumptions', ['tenant_id'], unique=False)
    op.create_table('police_matches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wanted_person_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('matched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'CONFIRMED', 'DISMISSED', name='police_match_status'), nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_police_matches_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_police_matches_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wanted_person_id'], ['wanted_persons.id'], name=op.f('fk_police_matches_wanted_person_id_wanted_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_police_matches'))
    )
    op.create_index(op.f('ix_police_matches_booking_id'), 'police_matches', ['booking_id'], unique=False)
    op.create_index(op.f('ix_police_matches_status'), 'police_matches', ['status'], unique=False)
    op.create_index(op.f('ix_police_matches_tenant_id'), 'police_matches', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_police_matches_wanted_person_id'), 'police_matches', ['wanted_person_id'], unique=False)
    op.create_index('uq_police_matches_person_booking', 'police_matches', ['wanted_person_id', 'booking_id'], unique=True)
    op.create_table('food_order_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('food_order_id', sa.UUID(), nullable=False),
    sa.Column('food_item_id', sa.UUID(), nullable=True),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_food_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_food_order_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], name=op.f('fk_food_order_items_food_item_id_food_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['food_order_id'], ['food_orders.id'], name=op.f('fk_food_order_items_food_order_id_food_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_food_order_items_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_order_items'))
    )
    op.create_index(op.f('ix_food_order_items_food_order_id'), 'food_order_items', ['food_order_id'], unique=False)
    op.create_index(op.f('ix_food_order_items_restaurant_id'), 'food_order_items', ['restaurant_id'], unique=False)
    op.create_table('platform_ledger_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('CREDIT', 'DEBIT', name='ledger_direction'), nullable=False),
    sa.Column('source_type', sa.Enum('BOOKING_COMMISSION', 'FOOD_ORDER_COMMISSION', 'MINIBAR_COMMISSION', 'SUBSCRIPTION_FEE', 'PAYOUT', 'REFUND', 'MANUAL_ADJUSTMENT', name='ledger_source_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('food_order_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_platform_ledger_entries_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], name=op.f('fk_platform_ledger_entries_account_id_platform_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_platform_ledger_entries_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['food_order_id'], ['food_orders.id'], name=op.f('fk_platform_ledger_entries_food_order_id_food_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_ledger_entries'))
    )
    op.create_index(op.f('ix_platform_ledger_entries_account_id'), 'platform_ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_platform_ledger_entries_booking_id'), 'platform_ledger_entries', ['booking_id'], unique=False)
    op.create_index(op.f('ix_platform_ledger_entries_food_order_id'), 'platform_ledger_entries', ['food_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_ledger_entries_food_order_id'), table_name='platform_ledger_entries')
    op.drop_index(op.f('ix_platform_ledger_entries_booking_id'), table_name='platform_ledger_entries')
    op.drop_index(op.f('ix_platform_ledger_entries_account_id'), table_name='platform_ledger_entries')
    op.drop_table('platform_ledger_entries')
    op.drop_index(op.f('ix_food_order_items_restaurant_id'), table_name='food_order_items')
    op.drop_index(op.f('ix_food_order_items_food_order_id'), table_name='food_order_items')
    op.drop_table('food_order_items')
    op.drop_index('uq_police_matches_person_booking', table_name='police_matches')
    op.drop_index(op.f('ix_police_matches_wanted_person_id'), table_name='police_matches')
    op.drop_index(op.f('ix_police_matches_tenant_id'), table_name='police_matches')
    op.drop_index(op.f('ix_police_matches_status'), table_name='police_matches')
    op.drop_index(op.f('ix_police_matches_booking_id'), table_name='police_matches')
    op.drop_table('police_matches')
    op.drop_index(op.f('ix_minibar_consumptions_tenant_id'), table_name='minibar_consumptions')
    op.drop_index(op.f('ix_minibar_consumptions_is_settled'), table_name='minibar_consumptions')
    op.drop_index(op.f('ix_minibar_consumptions_booking_id'), table_name='minibar_consumptions')
    op.drop_table('minibar_consumptions')
    op.drop_index(op.f('ix_food_orders_tenant_id'), table_name='food_orders')
    op.drop_index(op.f('ix_food_orders_status'), table_name='food_orders')
    op.drop_index(op.f('ix_food_orders_restaurant_id'), table_name='food_orders')
    op.drop_index(op.f('ix_food_orders_escrow_status'), table_name='food_orders')
    op.drop_index(op.f('ix_food_orders_booking_id'), table_name='food_orders')
    op.drop_table('food_orders')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_restaurant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_minibar_items_tenant_name', table_name='minibar_items')
    op.drop_index(op.f('ix_minibar_items_tenant_id'), table_name='minibar_items')
    op.drop_index(op.f('ix_minibar_items_category_id'), table_name='minibar_items')
    op.drop_table('minibar_items')
    op.drop_index('uq_food_items_restaurant_name', table_name='food_items')
    op.drop_index(op.f('ix_food_items_restaurant_id'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index('ix_bookings_tenant_check_in', table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_registry_hash'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_escrow_status'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('uq_rooms_tenant_room_number', table_name='rooms')
    op.drop_index(op.f('ix_rooms_tenant_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_state'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('uq_restaurants_tenant_name', table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_tenant_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_is_active'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index('uq_minibar_categories_tenant_name', table_name='minibar_categories')
    op.drop_index(op.f('ix_minibar_categories_tenant_id'), table_name='minibar_categories')
    op.drop_table('minibar_categories')
    op.drop_index(op.f('ix_wanted_persons_is_active'), table_name='wanted_persons')
    op.drop_table('wanted_persons')
    op.drop_index(op.f('ix_tenants_subscription_expires_at'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('uq_platform_accounts_singleton', table_name='platform_accounts')
    op.drop_table('platform_accounts')
    # ### end Alembic commands ###
