"""tenant platform fee percent

Revision ID: f361559f8a0b
Revises: b200544361f8
Create Date: 2026-07-22 04:33:33.118961+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f361559f8a0b'
down_revision: Union[str, None] = 'b200544361f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('platform_fee_percent', sa.Numeric(precision=5, scale=2), server_default='5.00', nullable=False))
    # ### end Alembic commands ###
    # Autogenerate does not emit CheckConstraints — add the range guard by hand.
    op.create_check_constraint(
        "platform_fee_percent_range",
        "tenants",
        "platform_fee_percent >= 0 AND platform_fee_percent <= 100",
    )


def downgrade() -> None:
    op.drop_constraint(
        "platform_fee_percent_range", "tenants", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'platform_fee_percent')
    # ### end Alembic commands ###
