"""police realm: officers, audit log, wanted district+status

Revision ID: 4838509f305a
Revises: c3d4e5f6a7b8
Create Date: 2026-07-09 07:50:10.097678+00:00
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

_RLS_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "enable_rls.sql"

revision: str = '4838509f305a'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add_column (unlike create_table) does NOT auto-emit CREATE TYPE, so
    # the enum must be created explicitly before the column references it.
    wanted_person_status = postgresql.ENUM(
        'WANTED', 'ARRESTED', 'CLEARED', name='wanted_person_status'
    )
    wanted_person_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('police_officers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('badge_number', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_police_officers')),
    sa.UniqueConstraint('badge_number', name=op.f('uq_police_officers_badge_number'))
    )
    op.create_table('police_audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_person_id', sa.UUID(), nullable=True),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['police_matches.id'], name=op.f('fk_police_audit_logs_match_id_police_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['officer_id'], ['police_officers.id'], name=op.f('fk_police_audit_logs_officer_id_police_officers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_person_id'], ['wanted_persons.id'], name=op.f('fk_police_audit_logs_target_person_id_wanted_persons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_police_audit_logs'))
    )
    op.create_index(op.f('ix_police_audit_logs_action'), 'police_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_police_audit_logs_officer_id'), 'police_audit_logs', ['officer_id'], unique=False)
    op.create_index(op.f('ix_police_audit_logs_target_person_id'), 'police_audit_logs', ['target_person_id'], unique=False)
    op.add_column('wanted_persons', sa.Column('district', sa.String(length=120), nullable=True))
    # server_default backfills existing watchlist rows to WANTED; the ORM
    # supplies the value on new inserts, so the default is harmless to keep.
    op.add_column('wanted_persons', sa.Column('status', postgresql.ENUM('WANTED', 'ARRESTED', 'CLEARED', name='wanted_person_status', create_type=False), nullable=False, server_default='WANTED'))
    op.create_index(op.f('ix_wanted_persons_status'), 'wanted_persons', ['status'], unique=False)
    # ### end Alembic commands ###

    # Re-apply the security posture so the new police-realm tables get their
    # grants, FORCE RLS and police_realm_only policy (script is idempotent;
    # the to_regclass guards make it safe on every prior revision too).
    sql = _RLS_SCRIPT.read_text(encoding="utf-8")
    sql = sql.replace("\nBEGIN;\n", "\n").replace("\nCOMMIT;\n", "\n")
    op.get_bind().exec_driver_sql(sql)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wanted_persons_status'), table_name='wanted_persons')
    op.drop_column('wanted_persons', 'status')
    op.drop_column('wanted_persons', 'district')
    op.drop_index(op.f('ix_police_audit_logs_target_person_id'), table_name='police_audit_logs')
    op.drop_index(op.f('ix_police_audit_logs_officer_id'), table_name='police_audit_logs')
    op.drop_index(op.f('ix_police_audit_logs_action'), table_name='police_audit_logs')
    op.drop_table('police_audit_logs')
    op.drop_table('police_officers')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS wanted_person_status")
